const str = `
.monaco-editor .bracket-highlighting-0 { color: #ffd700 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-1 { color: #da70d6 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-2 { color: #179fff !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-3 { color: #ffd700 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-4 { color: #da70d6 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-5 { color: #179fff !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-6 { color: #ffd700 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-7 { color: #da70d6 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-8 { color: #179fff !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-9 { color: #ffd700 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-10 { color: #da70d6 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-11 { color: #179fff !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-12 { color: #ffd700 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-13 { color: #da70d6 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-14 { color: #179fff !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-15 { color: #ffd700 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-16 { color: #da70d6 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-17 { color: #179fff !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-18 { color: #ffd700 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-19 { color: #da70d6 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-20 { color: #179fff !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-21 { color: #ffd700 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-22 { color: #da70d6 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-23 { color: #179fff !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-24 { color: #ffd700 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-25 { color: #da70d6 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-26 { color: #179fff !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-27 { color: #ffd700 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-28 { color: #da70d6 !important;text-shadow:none; }
.monaco-editor .bracket-highlighting-29 { color: #179fff !important;text-shadow:none; }
`
